### ISSUE TITLE
无法启动程序 缺少libstdc运行库

### ISSUE THREAD

**Issue by Riachel** [ez4y2f/SteamIconFix#1]
![图片](https://github.com/ez4y2f/SteamIconFix/assets/79738368/8dbe310f-bd83-4ba9-a917-87258833373c)
![图片](https://github.com/ez4y2f/SteamIconFix/assets/79738368/c68460ee-da48-4970-a87e-4fcadeafe85e)
如图所示 启动时会直接报错 
此外放入有运行库的文件夹时运行不会展示任何内容 而是弹出cmd窗口之后不到一秒消失 同时不会产生任何报错
![图片](https://github.com/ez4y2f/SteamIconFix/assets/79738368/8ae711b7-c2ed-4f44-bbb3-1eb8e6524000)

**Comment by ez4y2f** [comment]
最新的release已经改为静态编译，就是3.几mb的版本，应该能用了
在不带运行环境的win11虚拟机测试成功
